# TensorFlow

TensorFlow is an open-source machine learning framework developed by Google that helps developers build, train, and deploy machine learning and deep learning models. It provides tools for working with neural networks, data processing, and numerical computation at scale. TensorFlow is widely used for tasks such as image and speech recognition, natural language processing, recommendation systems, and predictive analytics. It supports running models on CPUs, GPUs, and mobile or embedded devices, making it suitable for both research and real-world applications.


---

# Installation

In [ ]:
!pip install tensorflow

Then verify installation:


In [65]:
import tensorflow as tf
import numpy as np
print(tf.__version__)
print(tf.keras.__version__)

2.19.1
3.11.3


---

# TensorFlow Fundamentals

## Creating tensors using `tf.constant()`

In [ ]:
vector = tf.constant(value, dtype=None, shape=None, name='Const')

In [6]:
# Creating matrix
matrix = tf.constant([[10, 7],
                      [7, 10],
                      [10,7]])
print(matrix)
print("ndim =", matrix.ndim)
print("shape =", matrix.shape)

tf.Tensor(
[[10  7]
 [ 7 10]
 [10  7]], shape=(3, 2), dtype=int32)
ndim = 2
shape = (3, 2)


I0000 00:00:1768727847.813604    3537 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3584 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6


In [ ]:
# Changing tensor [We cannot reassign in constants "It will give an error"]
unchangeable_tensor = tf.constant([10,7])
unchangeable_tensor[0].assign(8)
unchangeable_tensor

## Creating tensors using `tf.variable()`

In [8]:
changeable_tensor = tf.constant([10,7])
print(unchangeable_tensor)

tf.Tensor([10  7], shape=(2,), dtype=int32)


In [9]:
# Changing tensor
changeable_tensor = tf.Variable([10,7])
changeable_tensor[0].assign(8)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([8, 7], dtype=int32)>

## Creating random tensors

In [10]:
random_tensor = tf.random.Generator.from_seed(42)
random_tensor = random_tensor.normal(shape=(3,2))
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

## Shuffle elements order in a tensor
 - used in shuffling data

In [11]:
not_shuffled = tf.constant([[10, 7],
                           [3, 4],
                           [2, 5]])
print(not_shuffled.ndim)

2


In [12]:
# shuffle our not-shuffled
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [13]:
# shuffle our not-shuffled
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

## Create tensor from a numpy array

In [14]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [15]:
# numpy array to tensor
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [16]:
# reshape the tensor
B = tf.constant(numpy_A, shape=(2,3,4))
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

## Create a tensor of all ones

In [17]:
tf.ones([5,3])

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

## Create a tensor of all zeros

In [18]:
tf.zeros([5,3])

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

## Getting information from tensors

In [19]:
tensor = tf.zeros(shape=[2,3,4,5])

In [20]:
# index access
tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [21]:
# shape
tensor.shape

TensorShape([2, 3, 4, 5])

In [22]:
# dimensions/rank
tensor.ndim

4

In [23]:
# size
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [24]:
# data type
tensor.dtype

tf.float32

## Indexing and expanding tensors


In [25]:
tensor = tf.zeros(shape=[2,3,4,5])

# Get the first element from each dimension from each index except for the final one
tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
tensor2 = tf.constant([[10,7],[4,6]])

# Get the last element of each row
tensor2[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 6], dtype=int32)>

In [27]:
tensor3 = tf.constant([[1,2,3], [4,5,6], [7,8,9]])

# Insert another dimension
print(tensor3[tf.newaxis, :, :]) # => [[[1,2,3], [4,5,6], [7,8,9]]]
print(tensor3[:, tf.newaxis, :]) # => [[[1,2,3]], [[4,5,6]], [[7,8,9]]]
print(tensor3[:, :, tf.newaxis]) # => [[[1],[2],[3]], [[4],[5],[6]],[[7],[8],[9]]]

tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]]], shape=(1, 3, 3), dtype=int32)
tf.Tensor(
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]], shape=(3, 1, 3), dtype=int32)
tf.Tensor(
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]], shape=(3, 3, 1), dtype=int32)


## Tensor Operations

In [28]:
tensor = tf.constant([[10,7], [3,4]])

In [29]:
# addition
tensor + 10
# OR
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [30]:
# subtraction
tensor - 10
# OR
tf.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [31]:
# multiplication
tensor * 10
# OR
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [32]:
# division
tensor / 10
# OR
tf.divide(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [33]:
# square
tf.square(tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [34]:
# square root
tf.sqrt(tf.cast(tensor, dtype=tf.float32))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3.1622777, 2.6457512],
       [1.7320508, 2.       ]], dtype=float32)>

In [35]:
# log
tf.math.log(tf.cast(tensor, dtype=tf.float32))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.3025851, 1.9459102],
       [1.0986123, 1.3862944]], dtype=float32)>

## Matrix Multiplication (M * M)

In [36]:
tf1 = tf.constant([[10,7], [3,4]])
tf2 = tf.constant([[10,7], [3,4]])

tf.matmul(tf1, tf2)
#OR
tf1 @ tf2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

## Reshaping Matrix

In [37]:
tf1 = tf.constant([[10, 7],
                   [3, 4],
                   [1, 2]])  # shape = (3, 2)

In [38]:
# Reshape with specific dimensions
reshaped = tf.reshape(tf1, shape=(2, 3))
print("original shape:", tf1.shape)
print("reshaped shape:", reshaped.shape)
print(reshaped)

original shape: (3, 2)
reshaped shape: (2, 3)
tf.Tensor(
[[10  7  3]
 [ 4  1  2]], shape=(2, 3), dtype=int32)


In [39]:
# reshape with flipping the dimensions
reshaped = tf.transpose(tf1)
print("original shape:", tf1.shape)
print("reshaped shape:", reshaped.shape)
print(reshaped)

original shape: (3, 2)
reshaped shape: (2, 3)
tf.Tensor(
[[10  3  1]
 [ 7  4  2]], shape=(2, 3), dtype=int32)


In [40]:
# Difference between transpose and reshape
tensor = tf.constant([[10, 7],
                      [3, 4],
                      [1, 2]])  # shape = (3, 2)

print("original shape:", tensor.shape)
print("original:\n", tensor.numpy())

reshaped = tf.reshape(tensor, (2, 3))
print("reshaped shape:", reshaped.shape)
print("reshaped:\n", reshaped.numpy())

transposed = tf.transpose(tensor)
print("transposed shape:", transposed.shape)
print("transposed:\n", transposed.numpy())

original shape: (3, 2)
original:
 [[10  7]
 [ 3  4]
 [ 1  2]]
reshaped shape: (2, 3)
reshaped:
 [[10  7  3]
 [ 4  1  2]]
transposed shape: (2, 3)
transposed:
 [[10  3  1]
 [ 7  4  2]]


## Changing tensor data type

In [41]:
# default inger dtype
a = tf.constant([10,7])
a.dtype

tf.int32

In [42]:
# default float dtype
b = tf.constant([10.,7.])
b.dtype

tf.float32

In [43]:
# change dtype
a = tf.cast(a, dtype=tf.int16)
print('a:', a.dtype)

b = tf.cast(b, dtype=tf.float16)
print('b:',b.dtype)

a: <dtype: 'int16'>
b: <dtype: 'float16'>


## Tensor Aggregation

In [44]:
tensor = tf.constant(np.random.randint(-5, 100, size=50))
tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([24, 23, 79, 24, 15, 66, 70, 87, 55, 80, -2, 14, 27, 55, 14, 79, 80,
       33, 39, 91, 46, 31, 37, 50, 13, 37, 12, 32, 11,  0,  0, 52, -1, 78,
       59, 69, 27, 50, 54, 33, 66, 78, 36, 61, 49, 62, 63,  6, 28, 28])>

In [45]:
# abs
abs = tf.abs(tensor)
print(abs)

tf.Tensor(
[24 23 79 24 15 66 70 87 55 80  2 14 27 55 14 79 80 33 39 91 46 31 37 50
 13 37 12 32 11  0  0 52  1 78 59 69 27 50 54 33 66 78 36 61 49 62 63  6
 28 28], shape=(50,), dtype=int64)


In [46]:
# minimum
minimum = tf.reduce_min(tensor)
print(minimum)

tf.Tensor(-2, shape=(), dtype=int64)


In [47]:
# maximum
maximum = tf.reduce_max(tensor)
print(maximum)

tf.Tensor(91, shape=(), dtype=int64)


In [48]:
# sum
sum = tf.reduce_sum(tensor)
print(sum)

tf.Tensor(2120, shape=(), dtype=int64)


In [49]:
# mean
mean = tf.reduce_mean(tensor)
print(mean)

tf.Tensor(42, shape=(), dtype=int64)


In [50]:
# variance
var = tf.math.reduce_variance(tf.cast(tensor, dtype=tf.float32))
print(var)

tf.Tensor(670.08, shape=(), dtype=float32)


In [51]:
# standard deviation
std = tf.math.reduce_std(tf.cast(tensor, dtype=tf.float32))
print(std)

tf.Tensor(25.885904, shape=(), dtype=float32)


## Find positional maximun and minimum

In [52]:
tf.random.set_seed(42)
tensor = tf.random.uniform(shape=[50])
tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [53]:
# find positional maximum
positional_max = tf.argmax(tensor)
print(positional_max)

tf.Tensor(42, shape=(), dtype=int64)


In [54]:
# find positional minimum
positional_min = tf.argmin(tensor)
print(positional_min)

tf.Tensor(16, shape=(), dtype=int64)


## Squeezing a tensor
- remove all single dimensions

In [55]:
tf.random.set_seed(42)
g = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,50))
g

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [56]:
g.shape

TensorShape([1, 1, 1, 50])

In [57]:
g = tf.squeeze(g)
g.shape

TensorShape([50])

## One-hot Encoding

In [58]:
list = [0,1,2,3,4]

In [59]:
# one-hot encoding
tf.one_hot(list, depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [60]:
# one-hot encoding with axis=0
tf.one_hot(list, depth=5, axis=0)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [61]:
# one-hot encoding with axis=1
tf.one_hot(list, depth=5, axis=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

## TensorFlow with Numpy

In [62]:
# creating tensor from numpy array
t = tf.constant(np.array([1,2,3]))

In [63]:
# convert tensor to numpy
np.array(t), type(t.numpy())

(array([1, 2, 3]), numpy.ndarray)

---

# Optimizers, Losses, and Metrics

### Common Optimizers

* `tf.keras.optimizers.Adam()`
* `tf.keras.optimizers.SGD()`
* `tf.keras.optimizers.RMSprop()`

### Common Losses

* `sparse_categorical_crossentropy`
* `binary_crossentropy`
* `mean_squared_error`

### Common Metrics

* `accuracy`
* `precision`
* `recall`

---

# Key Components of TensorFlow + Keras

| Component                 | Description                           |
| ------------------------- | ------------------------------------- |
| **`tf.keras.models`**     | Create, save, and load models         |
| **`tf.keras.layers`**     | Define neural network layers          |
| **`tf.keras.optimizers`** | Optimize model weights                |
| **`tf.keras.losses`**     | Define loss functions                 |
| **`tf.keras.metrics`**    | Evaluate performance                  |
| **`tf.keras.callbacks`**  | Control training behavior             |
| **`tf.data`**             | Efficient input pipelines             |
| **`tf.function`**         | Convert Python to TF graphs for speed |

---


# Keras Functionalities Overview

| Functionality         | Description             |
| --------------------- | ----------------------- |
| **Sequential API**    | Simple models           |
| **Functional API**    | Complex models          |
| **Model Subclassing** | Full control            |
| **Callbacks**         | Control training flow   |
| **TensorBoard**       | Visualization           |
| **Checkpointing**     | Save best models        |
| **Transfer Learning** | Reuse pretrained models |
| **TFLite/TFJS**       | Deployment              |

---

## Check TensorFlow Running on GPU or CPU

In [ ]:
import tensorflow as tf
import os

# Suppress TensorFlow warnings (optional)
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'  # 0=all, 1=filter INFO, 2=filter WARNING, 3=filter ERROR

# Check TensorFlow version
print(f"TensorFlow Version: {tf.__version__}")

# Check GPU availability
print("\n" + "="*80)
print("GPU Configuration")
print("="*80)

# List physical devices
physical_devices = tf.config.list_physical_devices()
print(f"\nAll Physical Devices: {len(physical_devices)}")
for device in physical_devices:
    print(f"  - {device}")

# List GPU devices
gpus = tf.config.list_physical_devices('GPU')
print(f"\nGPU Devices Found: {len(gpus)}")
for i, gpu in enumerate(gpus):
    print(f"  GPU {i}: {gpu}")
    # Get GPU details
    gpu_details = tf.config.experimental.get_device_details(gpu)
    if gpu_details:
        print(f"    Details: {gpu_details}")

# Check if GPU is available
if gpus:
    print("\n✓ GPU is available and will be used for training!")
    try:
        # Set memory growth to prevent TensorFlow from allocating all GPU memory at once
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        print("✓ Memory growth enabled for GPU(s)")
    except RuntimeError as e:
        print(f"Memory growth setting error: {e}")
else:
    print("\n✗ No GPU found. Training will use CPU.")

# Verify CUDA and cuDNN
print(f"\nBuilt with CUDA: {tf.test.is_built_with_cuda()}")
print(f"GPU Available: {tf.test.is_gpu_available(cuda_only=False, min_cuda_compute_capability=None) if hasattr(tf.test, 'is_gpu_available') else 'N/A (deprecated)'}")

print("="*80 + "\n")

---